
package com.example.webService.AutoGeneratedCode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "HelloWorld", targetNamespace = "http://webService.example.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface HelloWorld {


    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webService.example.com/", className = "com.example.webService.AutoGeneratedCode.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webService.example.com/", className = "com.example.webService.AutoGeneratedCode.SayHelloResponse")
    @Action(input = "http://webService.example.com/HelloWorld/sayHelloRequest", output = "http://webService.example.com/HelloWorld/sayHelloResponse")
    String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
