package com.example.config;

//import com.example.webService.AutoGeneratedCode.HelloWorldService;
//import org.springframework.context.annotation.Bean;
//import org.springframework.context.annotation.Configuration;
//
///**
// * web service 的服务注入配置（启动这个配置文件的话，启动项目前必须启动webService包下的HelloWorld服务才能正常启动项目）
// *
// * @author zhangzhenyan
// * @since 2019-05-08
// **/
//@Configuration
//public class WebServiceConfig {
//
//    @Bean
//    public HelloWorldService getHelloWorldService() {
//        return new HelloWorldService();
//    }
//}
