package com.example.controller;

import com.alibaba.druid.util.StringUtils;
import com.example.constant.ResultCode;
import com.example.exception.ParamsCheckException;
import com.example.responseVo.ResultVo;
import com.example.webService.AutoGeneratedCode.HelloWorldService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * web service controller
 *
 * @author zhangzhenyan
 * @since 2019-05-08
 **/
@RestController(value = "/webService")
public class WebServiceController {

    private HelloWorldService helloWorldService;

    @Autowired
    public void setHelloWorldService(HelloWorldService helloWorldService) {
        this.helloWorldService = helloWorldService;
    }

    @GetMapping("/testWebService")
    public ResultVo testWebService(@RequestParam(value = "user_name") String name) {
        if (StringUtils.isEmpty(name)) {
            throw new ParamsCheckException(ResultCode.PARAMETER_ERROR);
        }
        return ResultVo.success(helloWorldService.getHelloWorldPort().sayHello(name));
    }
}
